#!/bin/bash

add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
add-apt-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"
apt-get update
apt-get install -y pure-ftpd pureadmin

sudo groupadd ftpgroup
sudo useradd -g ftpgroup -d /dev/null -s /etc ftpuser

sudo mkdir /home/ftpusers
sudo mkdir /home/ftpusers/recordings

echo "Enter password for user: recordings"
sudo pure-pw useradd recordings -u ftpuser -d /home/ftpusers/recordings
sudo pure-pw mkdb

sudo ln -s /etc/pure-ftpd/pureftpd.passwd /etc/pureftpd.passwd
sudo ln -s /etc/pure-ftpd/pureftpd.pdb /etc/pureftpd.pdb
sudo ln -s /etc/pure-ftpd/conf/PureDB /etc/pure-ftpd/auth/PureDB

sudo chown -hR ftpuser:ftpgroup /home/ftpusers/

